### ISSUE TITLE
Matlab-GUI install fail

### ISSUE THREAD

**Issue by jasonbirdd** [cabooster/DeepCAD-RT#17]
Hi cabooster! I tried to use matlab GUI for testing my dataset. However, when I command `installDeepCADRT` after `mex -setup C++`, 
I faced this problem.

`Compiling cpp file to accelerate denoising...
Building with 'MinGW64 Compiler (C++)'.
**Error using mex
In file included from E:\110011566\research_denoise\DeepCAD-RT-v2.3.5\DeepCAD-RT-v2\buffers.h:20:0,
                 from E:\110011566\research_denoise\DeepCAD-RT-v2.3.5\DeepCAD-RT-v2\deepcadrt_core.cpp:3:
E:\110011566\research_denoise\DeepCAD-RT-v2.3.5\DeepCAD-RT-v2\common.h:27:19: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
                   ^
compilation terminated.
Error using mex
In file included from E:\110011566\research_denoise\DeepCAD-RT-v2.3.5\DeepCAD-RT-v2\buffers.h:20:0,
                 from E:\110011566\research_denoise\DeepCAD-RT-v2.3.5\DeepCAD-RT-v2\deepcadrt_core.cpp:3:
E:\110011566\research_denoise\DeepCAD-RT-v2.3.5\DeepCAD-RT-v2\common.h:27:19: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
                   ^
compilation terminated.

Error in installDeepCADRT (line 5)
mex deepcadrt_core.cpp -lcudart.lib -lcublas.lib -lnvinfer.lib -lnvinfer_plugin.lib -lnvparsers.lib -lmyelin64_1.lib -lopencv_world341.lib -lpthreadVC2.lib -llibtiff.lib`

Error in installDeepCADRT (line 5)
mex deepcadrt_core.cpp -lcudart.lib -lcublas.lib -lnvinfer.lib -lnvinfer_plugin.lib -lnvparsers.lib -lmyelin64_1.lib -lopencv_world341.lib -lpthreadVC2.lib -llibtiff.lib`**

I followed the steps in matlab-GUI readme, is there anything I missed?

**Comment by cabooster** [comment]
Hi jasonbirdd! 

- This error is because your C++ compiler is `MinGW64 Compiler` instead of `Microsoft Visual C++`. After you install Visual Studio 2017, you can choose this as the compiler after typing in `mex -setup C++` (as the figure shown below).

![image](https://user-images.githubusercontent.com/53425563/195856814-ceba4779-7722-49e3-8845-08c201ff31e9.png)

For this example, after I type in `mex -setup:D:\MATLAB\R2018b\bin\win64\mexopts\msvcpp2017.xml C++`,  `Microsoft Visual C++` becomes my C++ compiler. 

- Please also check your environment according to our required environment which is shown in the Matlab-GUI Readme. Thank you.

1. Windows 10
2. CUDA 11.0
3. CUDNN 8.0.5
4. Matlab 2018a (or newer version)
5. Visual Studio 2017

**Comment by jasonbirdd** [comment]
OK!

> Hi jasonbirdd!
> 
> * This error is because your C++ compiler is `MinGW64 Compiler` instead of `Microsoft Visual C++`. After you install Visual Studio 2017, you can choose this as the compiler after typing in `mex -setup C++` (as the figure shown below).
> 
> ![image](https://user-images.githubusercontent.com/53425563/195856814-ceba4779-7722-49e3-8845-08c201ff31e9.png)
> 
> For this example, after I type in `mex -setup:D:\MATLAB\R2018b\bin\win64\mexopts\msvcpp2017.xml C++`, `Microsoft Visual C++` becomes my C++ compiler.
> 
> * Please also check your environment according to our required environment which is shown in the Matlab-GUI Readme. Thank you.
> 
> 1. Windows 10
> 2. CUDA 11.0
> 3. CUDNN 8.0.5
> 4. Matlab 2018a (or newer version)
> 5. Visual Studio 2017

OK! I'll try it. Thank you a lot!
