### ISSUE TITLE
Request for clarifications on training on our own datasets

### ISSUE THREAD

**Issue by tianxi-zoe** [cabooster/DeepCAD-RT#22]
Hi there,

I have already tried the demo models and datasets, which work well. When I tried with my own dataset, I got some problems.
1. I was only able to start training when I put one video in the train_dataset, which is also the case for the demo. If I put more than two videos, it gives me a 'Killed Job' Error. I also checked other datasets you provided, and they seem to be all in one video. I am wondering if I should concatenate them together in one video (I have eight low SNR videos in total).
2. Is it possible to resume training? For example, I have trained a model for around 300 epochs, is it possible for me to use that model and continue training? 
3. I don't quite understand how it works if we have low SNR videos and high SNR videos based on the first question when I was able to put one video to train. Do we just use high SNR to validate? If so, how are we going to achieve that?
4. I don't understand what datasize and patch_xy/t refer to. For example, if I have a video of size 1024x1024 and has 3000 frames, is the datasize 3000? What about the patches?

Thank you so much in advance!

**Comment by cabooster** [comment]
Hi!
1. I put multiple `.tif` files in the datasets folder, and it works well. You do not need to concatenate them together in one video. If you could share your data and the parameter setting with us, that's would be helpful to solve your problem.
2. You can load the last model saved in the model folder to resume training before starting the training loop. This issue is similar to the solved issue #10.  Please refer to the explanation there for more detail.
3.  Our method only needs low SNR input. The high SNR videos shown in our paper are only used for validation. Therefore, you just need to put low SNR videos in your train folder.
4. Before the `.tif` file is sent into the network, it will be partitioned into multiple 3D patches. `train_datasets_size` refers to the number of 3D patches extracted in each epoch. `patch_xy/t` means the size of the 3D patches. The default patch_xy/patch_t is 150, and train_datasets_size is 6000.  In most cases, you don't need to change it.

**Comment by tianxi-zoe** [comment]
Sorry for the late reply. Thank you for the answer!

Sure, I can share some of the data with you. Do you have an email address so that I can send you the Google drive link?

**Comment by cabooster** [comment]
My email address: 22110720036@m.fudan.edu.cn.  If you could share **your data and the parameter setting** with us, that's would be helpful to solve your problem.

**Comment by cabooster** [comment]
1. Most of the training parameters are correct. But the `n_epochs` can be set to 20. It is enough.

2. The parameter `test_datasize` is used to adjust the test frame number. We have updated the code comments and default parameter values.
![image](https://user-images.githubusercontent.com/71710781/226507426-ae6a01cf-1928-41af-83ed-a0e215e69f51.png)

**Comment by tianxi-zoe** [comment]
Thank you for your answer! 
But I still got the job killed when I put eight videos into the training dataset. I have set the number of epochs to 20. Do you have any ideas why I keep getting this problem?

**Comment by cabooster** [comment]
You can try to train four videos or two videos. If the job is not killed, the size of the RAM may not be enough.

**Comment by tianxi-zoe** [comment]
Okay, that makes sense. Increasing the RAM makes it work for 8 videos!!! Thanks a lot!!

**Comment by GUO-neuroLAB** [comment]
Hi, I got the same problem when I test my 5000 frame data ,and it output 2500 frames.  I noticed that when I train the model ,it seems 2500 input but my tiff is 5000 frames. how can I adjust the code.
