### ISSUE TITLE
model .zip file for Fiji?

### ISSUE THREAD

**Issue by pkells12** [cabooster/DeepCAD-RT#7]
I believe I've successfully trained a model (many E_*_Iter_*.pth files stored in /pth/) but am unable to find a .zip file in the directory structure. 

Is there a way to perform denoising on subsequent movies without using the Fiji plugin? I may be missing something but it doesn't seem like the two methods (Fiji plugin and DeepCAD-RT) overlap.

I hope I'm making my issue clear. Let me know if you need further clarification.

**Comment by cabooster** [comment]
Hi, pkells12. I think you can directly use the python code to perform denoising on subsequent movies. You can do this by run 
`python test.py --denoise_model the_folder_containing_your_model --datasets_folder the_folder_containing_your_data --GPU 0 --batch_size 1 --test_datasize 100000`
The Fiji plugin is only compatible with Tensorflow and its model should be trained with Tensorflow too. We recommend the Pytorch implementation since it's much faster and has better performance. I hope this is helpful for you.

**Comment by pkells12** [comment]
Ah, I see. It's working great now. Thanks!
