### ISSUE TITLE
Model training for separate field of views

### ISSUE THREAD

**Issue by cgaletzka** [cabooster/DeepCAD-RT#9]
Hi, thank you for providing this great software!

It was mentioned in issue #5 that a new model should be trained for each set of data. Does that mean that each field of view should have its own model? In my case, I have recordings from the cerebellar surface from three different field of views so I am wondering if I should train three separate models.

**Comment by cabooster** [comment]
Hi, cgaletzka. In issue #5,  there may be too much diversity in 25 recordings. If your data come from the same sample and similar imaging parameters, you can train one model to handle these data. And we recommend you place data from three different fields of view into your training folder. In addition, you can directly use the model file in the last epoch because we solve the overfitting problem in the previous version.

**Comment by cgaletzka** [comment]
Great, that's very helpful. Thank you so much!
